apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    custom-kubelet: cpumanager-enabled
    machineconfiguration.openshift.io/role: worker-epa
  name: worker-epa
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - worker
      - worker-epa
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-epa: ""
  paused: false
