apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: rt-performanceprofile
spec:
  additionalKernelArgs:
    - nmi_watchdog=0
    - audit=0
    - mce=off
    - processor.max_cstate=1
    - idle=poll
    - intel_idle.max_cstate=0
  cpu:
    isolated: 3-5
    reserved: 0-2
  machineConfigPoolSelector:
    machineconfiguration.openshift.io/role: worker-epa
  nodeSelector:
    node-role.kubernetes.io/worker-epa: ''
  numa:
    topologyPolicy: "single-numa-node"
  realTimeKernel:
    enabled: true
